- generic [ref=e6]:
  - img "Unitree" [ref=e7]
  - heading "欢迎登录" [level=1] [ref=e8]
  - paragraph [ref=e9]: Unitree 协作平台
  - generic [ref=e10]:
    - textbox "用户名（YouTrack 登录名，如 zhiyu.yang）" [active] [ref=e12]
    - textbox "密码" [ref=e14]
    - button "登 录" [ref=e15] [cursor=pointer]
  - generic [ref=e18]: 或
  - button "使用 YouTrack 账号登录" [ref=e20] [cursor=pointer]
  - paragraph [ref=e21]: 首次登录默认密码为 123，登录后请及时修改